version: '3.8'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/backend-test
      - JWT_SECRET=Q5uVgLC3lLQikyQdFdZwey4D
      - GOOGLE_MAPS_API_KEY=your_google_maps_api_key
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
